version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: recallguard
      POSTGRES_PASSWORD: recallguard
      POSTGRES_DB: recallguard
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7
    restart: always
    ports: ["6379:6379"]

  # ───────── backend API ─────────
  api:
    build:
      context: .            # ← repo root
      dockerfile: backend/Dockerfile
    env_file: .env
    depends_on: [db, redis]
    ports: ["5000:5000"]

  # ───────── Celery worker ───────
  worker:
    build:
      context: .            # ← repo root
      dockerfile: celery/Dockerfile
    env_file: .env
    depends_on: [db, redis]

  # ───────── Next.js frontend ────
  frontend:
    build:
      context: .            # ← repo root
      dockerfile: frontend/Dockerfile
    env_file: .env
    depends_on: [api]
    ports: ["3000:3000"]

volumes:
  postgres_data:
