version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: recallguard
      POSTGRES_USER: recallguard
      POSTGRES_DB: recallguard
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
  worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    env_file: .env
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"
