version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: recallguard
      POSTGRES_USER: recallguard
      POSTGRES_DB: recallguard
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
